// Generated by gencpp from file gripper_2f85/SetPositionRequest.msg
// DO NOT EDIT!


#ifndef GRIPPER_2F85_MESSAGE_SETPOSITIONREQUEST_H
#define GRIPPER_2F85_MESSAGE_SETPOSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gripper_2f85
{
template <class ContainerAllocator>
struct SetPositionRequest_
{
  typedef SetPositionRequest_<ContainerAllocator> Type;

  SetPositionRequest_()
    : GoalPosition(0)  {
    }
  SetPositionRequest_(const ContainerAllocator& _alloc)
    : GoalPosition(0)  {
  (void)_alloc;
    }



   typedef uint8_t _GoalPosition_type;
  _GoalPosition_type GoalPosition;





  typedef boost::shared_ptr< ::gripper_2f85::SetPositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gripper_2f85::SetPositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetPositionRequest_

typedef ::gripper_2f85::SetPositionRequest_<std::allocator<void> > SetPositionRequest;

typedef boost::shared_ptr< ::gripper_2f85::SetPositionRequest > SetPositionRequestPtr;
typedef boost::shared_ptr< ::gripper_2f85::SetPositionRequest const> SetPositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gripper_2f85::SetPositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gripper_2f85::SetPositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gripper_2f85

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'gazebo_msgs': ['/opt/ros/melodic/share/gazebo_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/melodic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gripper_2f85::SetPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gripper_2f85::SetPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gripper_2f85::SetPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gripper_2f85::SetPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_2f85::SetPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_2f85::SetPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gripper_2f85::SetPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f64e23e3abae17383a7f4dcd52672d34";
  }

  static const char* value(const ::gripper_2f85::SetPositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf64e23e3abae1738ULL;
  static const uint64_t static_value2 = 0x3a7f4dcd52672d34ULL;
};

template<class ContainerAllocator>
struct DataType< ::gripper_2f85::SetPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gripper_2f85/SetPositionRequest";
  }

  static const char* value(const ::gripper_2f85::SetPositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gripper_2f85::SetPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 GoalPosition\n\
";
  }

  static const char* value(const ::gripper_2f85::SetPositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gripper_2f85::SetPositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.GoalPosition);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gripper_2f85::SetPositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gripper_2f85::SetPositionRequest_<ContainerAllocator>& v)
  {
    s << indent << "GoalPosition: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.GoalPosition);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRIPPER_2F85_MESSAGE_SETPOSITIONREQUEST_H
