// Generated by gencpp from file gripper_2f85/SetPosition.msg
// DO NOT EDIT!


#ifndef GRIPPER_2F85_MESSAGE_SETPOSITION_H
#define GRIPPER_2F85_MESSAGE_SETPOSITION_H

#include <ros/service_traits.h>


#include <gripper_2f85/SetPositionRequest.h>
#include <gripper_2f85/SetPositionResponse.h>


namespace gripper_2f85
{

struct SetPosition
{

typedef SetPositionRequest Request;
typedef SetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPosition
} // namespace gripper_2f85


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gripper_2f85::SetPosition > {
  static const char* value()
  {
    return "87d400ec63405a5a482ebb7ac498cbfb";
  }

  static const char* value(const ::gripper_2f85::SetPosition&) { return value(); }
};

template<>
struct DataType< ::gripper_2f85::SetPosition > {
  static const char* value()
  {
    return "gripper_2f85/SetPosition";
  }

  static const char* value(const ::gripper_2f85::SetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::gripper_2f85::SetPositionRequest> should match 
// service_traits::MD5Sum< ::gripper_2f85::SetPosition > 
template<>
struct MD5Sum< ::gripper_2f85::SetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gripper_2f85::SetPosition >::value();
  }
  static const char* value(const ::gripper_2f85::SetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gripper_2f85::SetPositionRequest> should match 
// service_traits::DataType< ::gripper_2f85::SetPosition > 
template<>
struct DataType< ::gripper_2f85::SetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::gripper_2f85::SetPosition >::value();
  }
  static const char* value(const ::gripper_2f85::SetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gripper_2f85::SetPositionResponse> should match 
// service_traits::MD5Sum< ::gripper_2f85::SetPosition > 
template<>
struct MD5Sum< ::gripper_2f85::SetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gripper_2f85::SetPosition >::value();
  }
  static const char* value(const ::gripper_2f85::SetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gripper_2f85::SetPositionResponse> should match 
// service_traits::DataType< ::gripper_2f85::SetPosition > 
template<>
struct DataType< ::gripper_2f85::SetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::gripper_2f85::SetPosition >::value();
  }
  static const char* value(const ::gripper_2f85::SetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRIPPER_2F85_MESSAGE_SETPOSITION_H
