// Generated by gencpp from file gripper_2f85/SetPositionResponse.msg
// DO NOT EDIT!


#ifndef GRIPPER_2F85_MESSAGE_SETPOSITIONRESPONSE_H
#define GRIPPER_2F85_MESSAGE_SETPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gripper_2f85
{
template <class ContainerAllocator>
struct SetPositionResponse_
{
  typedef SetPositionResponse_<ContainerAllocator> Type;

  SetPositionResponse_()
    : Success(false)  {
    }
  SetPositionResponse_(const ContainerAllocator& _alloc)
    : Success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _Success_type;
  _Success_type Success;





  typedef boost::shared_ptr< ::gripper_2f85::SetPositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gripper_2f85::SetPositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetPositionResponse_

typedef ::gripper_2f85::SetPositionResponse_<std::allocator<void> > SetPositionResponse;

typedef boost::shared_ptr< ::gripper_2f85::SetPositionResponse > SetPositionResponsePtr;
typedef boost::shared_ptr< ::gripper_2f85::SetPositionResponse const> SetPositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gripper_2f85::SetPositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gripper_2f85::SetPositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gripper_2f85

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'gazebo_msgs': ['/opt/ros/melodic/share/gazebo_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/melodic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gripper_2f85::SetPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gripper_2f85::SetPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gripper_2f85::SetPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gripper_2f85::SetPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_2f85::SetPositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_2f85::SetPositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gripper_2f85::SetPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abd997250d7310d216110d082cc17cc0";
  }

  static const char* value(const ::gripper_2f85::SetPositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xabd997250d7310d2ULL;
  static const uint64_t static_value2 = 0x16110d082cc17cc0ULL;
};

template<class ContainerAllocator>
struct DataType< ::gripper_2f85::SetPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gripper_2f85/SetPositionResponse";
  }

  static const char* value(const ::gripper_2f85::SetPositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gripper_2f85::SetPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool Success\n\
\n\
";
  }

  static const char* value(const ::gripper_2f85::SetPositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gripper_2f85::SetPositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gripper_2f85::SetPositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gripper_2f85::SetPositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "Success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRIPPER_2F85_MESSAGE_SETPOSITIONRESPONSE_H
